services:
  make_up_service_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: "iwa_backend/makeUpServiceDB.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_make_up_service_data:/var/lib/postgresql/data
volumes:
  postgres_make_up_service_data: